rvm:
  - 1.8.7
  - 1.9.3
  - 2.2.0
  - 2.5.1
sudo: false
env:
  - "RACK='~>1.5.0'"
  - "RACK='~>1.4.0'"
  - "RACK='~>1.3.0'"
  - "AR='~>2.3'"
  - "AR='~>3.2.0'"
  - "AR='~>4.1'"
install: bundle install --without development
script: bundle exec rake test
